import { Navbar } from "@/component/app/navbar";
import "../styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const asyncStorage = require("next/dist/client/components/static-generation-async-storage.external")
  // //@ts-ignore
  // const staticStore = (fetch as any).__nextGetStaticStore?.() || asyncStorage.staticGenerationAsyncStorage;
  // const store = staticStore.getStore();
  // store.isOnDemandRevalidate = store.isOnDemandRevalidate && !(process.env.OPEN_NEXT_ISR === 'true');
  return (
    <html lang="en" data-theme="light">
      <head>
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>

      <body id="root">
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
